FROM ppc64le/alpine:latest

LABEL package="mopidy", version="3.0.2-r4", arch="ppc64le"

RUN apk add --update \
        mopidy=3.0.2-r4 \
    && rm -rf /var/cache/apk/*

EXPOSE 6600 6680 5555/udp
CMD ["/usr/local/bin/mopidy", "--save-debug-log"]
