FROM arm32v6/alpine:latest

LABEL package="mopidy", version="3.2.0-r3", arch="armhf"

RUN apk add --update \
        mopidy=3.2.0-r3 \
    && rm -rf /var/cache/apk/*

EXPOSE 6600 6680 5555/udp
CMD ["/usr/local/bin/mopidy", "--save-debug-log"]
