FROM arm64v8/alpine:latest

LABEL package="privoxy", version="3.0.29-r0", arch="aarch64"

RUN apk add --update \
        privoxy=3.0.29-r0 \
    && rm -rf /var/cache/apk/*

ENTRYPOINT ["privoxy"]
CMD []
