FROM arm32v7/alpine:latest

LABEL package="privoxy", version="3.0.32-r0", arch="armv7"

RUN apk add --update \
        privoxy=3.0.32-r0 \
    && rm -rf /var/cache/apk/*

ENV CONFFILE=/etc/privoxy/config
ENV PIDFILE=/var/run/privoxy.pid

ENTRYPOINT ["/usr/sbin/privoxy"]
CMD ["--no-daemon", "--pidfile", "${PIDFILE}", "${CONFFILE}"]
