FROM arm64v8/alpine:latest

LABEL package="postfix", version="3.7.0-r2", arch="aarch64"

RUN apk add --update \
        postfix=3.7.0-r2 \
    && rm -rf /var/cache/apk/*

EXPOSE 25
EXPOSE 465
USER root
WORKDIR "/var/spool/postfix"
ENTRYPOINT ["/usr/libexec/postfix/postfix-script", "start-fg"]

