FROM arm32v7/alpine:latest

LABEL package="postfix", version="3.6.4-r0", arch="armv7"

RUN apk add --update \
        postfix=3.6.4-r0 \
    && rm -rf /var/cache/apk/*

EXPOSE 25
EXPOSE 465
USER root
WORKDIR "/var/spool/postfix"
ENTRYPOINT ["/usr/libexec/postfix/postfix-script", "start-fg"]

