FROM mips64/alpine:latest

LABEL package="postfix", version="3.5.8-r0", arch="mips64"

RUN apk add --update \
        postfix=3.5.8-r0 \
    && rm -rf /var/cache/apk/*

EXPOSE 25
EXPOSE 465
USER root
WORKDIR "/var/spool/postfix"
ENTRYPOINT ["/usr/libexec/postfix/postfix-script", "start-fg"]

